export const FETCH_REQUEST_SNEAKERS = 'FETCH_REQUEST_SNEAKERS';
export const FETCH_REQUEST_SNEAKERS_SUCCESS = 'FETCH_REQUEST_SNEAKERS_SUCCESS';
export const FETCH_REQUEST_SNEAKERS_ERROR = 'FETCH_REQUEST_SNEAKERS_ERROR';