export const FETCH_REQUEST_SNEAKERS = 'FETCH_REQUEST_SNEAKERS';
export const FETCH_REQUEST_SNEAKERS_SUCCESS = 'FETCH_REQUEST_SNEAKERS_SUCCESS';
export const FETCH_REQUEST_SNEAKERS_ERROR = 'FETCH_REQUEST_SNEAKERS_ERROR';

export const FETCH_REQUEST_BRANDS = 'FETCH_REQUEST_BRANDS';
export const FETCH_REQUEST_BRANDS_SUCCESS = 'FETCH_REQUEST_BRANDS_SUCCESS';
export const FETCH_REQUEST_BRANDS_ERROR = 'FETCH_REQUEST_BRANDS_ERROR';

export const SEARCH_TEXT = 'SEARCH_TEXT';